### ISSUE TITLE
OOM Error in Gemini 2 2B TFLite Conversion with Quantization on 80GB RAM

### ISSUE THREAD

**Issue by KennethanCeyer** [google-ai-edge/ai-edge-torch#192]
I’m encountering out-of-memory (OOM) errors when attempting to convert Gemini 2 2b it using the AI Edge Torch conversion process on a Google Colab A100 runtime with approximately 80GB of RAM. The memory size here refers to regular memory, not GPU memory. (I understand that AI Edge Torch is currently not utilizing the GPU).

Despite following the[ MediaPipe user guidelines](https://ai.google.dev/edge/mediapipe/solutions/genai/llm_inference#gemma-2_2b), which recommend using TensorFlow Lite (TFLite) conversion, there’s no clear documentation specifying the required hardware specifications to ensure smooth operation without errors.

> Although the minimum requirement of 32GB is listed in [this document](https://github.com/google-ai-edge/ai-edge-torch/tree/main/ai_edge_torch/generative#known-issues), I'm encountering OOM issues even in an 80GB environment when converting the minimal number of parameter model for Gemma 2.

This has made it challenging to complete the conversion process. I’d appreciate any insights into the recommended hardware specs for handling the conversion of Gemini 2 2b it, especially regarding memory and GPU requirements.

**Current Colab Setup:**
- Colab Pro
- A100 GPU with 80GB memory

**Colab link:**
https://colab.research.google.com/drive/19h3SZBiWuGqqtddHbF5MzOFGbPahXPIv?usp=sharing

**AI Edge Conversion Code:**
https://github.com/KennethanCeyer/gemma2-to-tflite/blob/main/convert.py

**Comment by haozha111** [comment]
the OOM probably happens at quantization step. We've done some significant memory reduction on converter part, but we recently found quantization will take another huge chunk of memory space. As a first step, can you try to remove `quant_config` from the conversion step and see if you can get a float tflite model without issues? thanks!

**Comment by KennethanCeyer** [comment]
@haozha111 

I’ll share the Colab code with quantization disabled as mentioned earlier. Since the goal of converting to tflite is for Edge ML serving, we’ll need a solution for the OOM issue in the quantization step, if that indeed turns out to be the cause. (I’ll update the title accordingly when we reach that point.)

If the issue is confirmed to be quantization-related, it would be helpful to get guidance on whether it should be addressed within this project through a PR or tackled separately in a dedicated PyTorch quantization project. Before that, I’ll leave a comment once we confirm if the OOM issue is resolved with quantization disabled.

Thank you for your prompt response.

**Comment by haozha111** [comment]
Thanks for sharing the latest info.

For the 50+GB memory usage inside TF Lite converter step, which TF version are you currently using? if you are installing the dependencies based on https://github.com/google-ai-edge/ai-edge-torch/blob/84c501503eea48129be9a8b369c5f1f5b6e89e00/requirements.txt#L9 (which is 0722 version), the converter memory fixes are not fully included in this TF version. You probably need to update the tf-nightly version to a version number after September and see if that helps reduce the memory usage. Let me know if you find the converter memory reduces after this change.

**Comment by KennethanCeyer** [comment]
The device used for testing follows the dependency versions specified in the requirements.txt file of the [google-ai-edge/ai-edge-torch](https://github.com/google-ai-edge/ai-edge-torch/) repository.

![image](https://github.com/user-attachments/assets/7097c8ad-22db-4491-ab8a-aab9e3829116)

Today, I ran tests under the same conditions (with quantization disabled) using the updated tf-nightly>=2.18.0.dev20240722 package version. However, this did not result in any performance improvements; instead, the peak memory usage increased to `83.1GB`.

It seems that further detailed profiling and optimization of the memory usage during these stages will be necessary moving forward.

![image](https://github.com/user-attachments/assets/7f77721b-9a0c-4fc7-86c4-71297907c5e2)

**Comment by haozha111** [comment]
Thanks for the info. We will do more analysis here and get back to you.

**Comment by aravindmurali22** [comment]
Hi @KennethanCeyer , Since this issue was opened, significant updates and improvements have been released that may have already addressed your concern. We are closing this issue to maintain a current and relevant backlog. Please test using the latest version of the library. If the issue persists, kindly open a new report with updated reproduction steps so we can investigate it within our current development workflow.
Thank you.
