### ISSUE TITLE
nn.LayerNorm produces correct output on CPU but wrong output on GPU in exported TFLite models (AI Edge Torch ≥ 0.4.0)

### ISSUE THREAD

**Issue by kadu-v** [google-ai-edge/ai-edge-torch#718]
### Description of the bug:

Exported nn.LayerNorm TFLite models output correct values on CPU but zeros on GPU in AI Edge Torch ≥ 0.4 .0.

### Actual vs expected behavior:

Expected behaviour
- The exported TFLite model should yield identical outputs on CPU and GPU for the same input tensor.

Actual behaviour
- CPU execution returns the correct normalized values.
- GPU execution returns zeros for all but the first four elements.

Example log (input = all-ones tensor, shape 1 × 4 × 4 × 4):
```bash
✅ Output match at index 0:  0.7882136
✅ Output match at index 1:  1.1679684
✅ Output match at index 2: -1.2030246
✅ Output match at index 3: -0.7531573
❌ Output mismatch at index 4:  GPU: 0  CPU: 0.78821355
...
❌ Output mismatch at index 63: GPU: 0  CPU: -0.75315726
```

## Minimal example code for creating a model
```
import ai_edge_torch
import tensorflow as tf
import torch
import torch.nn as nn

torch.manual_seed(0)


class Bug2Model(nn.Module):
    def __init__(self):
        super(Bug2Model, self).__init__()
        in_channels = 4
        out_channels = 4
        self.conv = nn.Conv2d(
            in_channels=in_channels,
            out_channels=out_channels,
            kernel_size=1,
            stride=1,
            padding=0,
        )
        self.layer_norm = nn.LayerNorm(out_channels, eps=1e-6)

    def forward(self, x):
        x = self.conv(x)
        x = x.permute(0, 2, 3, 1)  # Change to channel last format
        x = self.layer_norm(x)
        return x


def main():
    model = Bug2Model()
    model = model.eval()

    sample_inputs = (torch.randn(1, 4, 4, 4),)
    model = ai_edge_torch.to_channel_last_io(model, args=[0])
    tfl_converter_flags = {"optimizations": [tf.lite.Optimize.DEFAULT]}
    edge_model = ai_edge_torch.convert(
        model,
        sample_args=sample_inputs,
        _ai_edge_converter_flags=tfl_converter_flags,
    )
    edge_model.export("bug2.tflite")

    # Run the model on PyTorch and TFLite
    x = torch.zeros(1, 4, 4, 4)
    print("Execute model on pytorch")
    y = model(x)
    print(y)

    print("Execute model on tflite")
    interpreter = tf.lite.Interpreter(model_path="bug2.tflite")
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    interpreter.set_tensor(input_details[0]["index"], x.numpy())
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]["index"])
    print(output_data)

    # Check if the outputs are close enough
    if torch.allclose(torch.tensor(output_data), y, atol=1e-5):
        print("Outputs are close enough!")
    else:
        print("Outputs are not close enough!")


if __name__ == "__main__":
    main()
```

> [!NOTE]
> A generated model and full example code are [here](https://github.com/kadu-v/ai-edge-torch-bugs-report)

**Comment by pkgoogle** [comment]
Hi @kadu-v, thanks for the report... do you happen to know the exact version/commit of ai-edge-torch you might be using? I followed your instructions in your repo (thanks for that), but i'm seeing this issue:

```sh
source .venv/bin/activate
(ai-edge-torch-bugs-report) xxxx@xxxxx:~/git/ai-edge-torch-bugs-report$ uv run bug2/bug2.py
2025-06-16 23:16:16.735107: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1750115776.752044 1871435 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1750115776.756839 1871435 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1750115776.771829 1871435 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750115776.771874 1871435 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750115776.771880 1871435 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1750115776.771892 1871435 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-06-16 23:16:16.775908: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/xxxxxx/git/ai-edge-torch-bugs-report/bug2/bug2.py", line 1, in <module>
    import ai_edge_torch
  File "/xxxxxx/git/ai-edge-torch-bugs-report/.venv/lib/python3.10/site-packages/ai_edge_torch/__init__.py", line 16, in <module>
    from ai_edge_torch._convert.converter import convert
  File "/xxxxxx/git/ai-edge-torch-bugs-report/.venv/lib/python3.10/site-packages/ai_edge_torch/_convert/converter.py", line 20, in <module>
    from ai_edge_torch import model
  File "/xxxxxx/git/ai-edge-torch-bugs-report/.venv/lib/python3.10/site-packages/ai_edge_torch/model.py", line 30, in <module>
    from ai_edge_litert import interpreter as tfl_interpreter  # pylint: disable=g-direct-tensorflow-import
  File "/xxxxxx/git/ai-edge-torch-bugs-report/.venv/lib/python3.10/site-packages/ai_edge_litert/interpreter.py", line 34, in <module>
    from ai_edge_litert import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /xxxxxx/git/ai-edge-torch-bugs-report/.venv/lib/python3.10/site-packages/ai_edge_litert/_pywrap_tensorflow_interpreter_wrapper.so: cannot enable executable stack as shared object requires: Invalid argument

**Comment by kadu-v** [comment]
@pkgoogle Thank you for your reply.
Below is the complete list of dependencies (output of uv pip freeze):
```zsh
(ai-edge-torch-bugs-report) vscode ➜ /workspaces/ai-edge-torch-bugs-report (main) $ uv pip freeze                  

absl-py==2.3.0
ai-edge-litert==1.2.0
ai-edge-quantizer==0.1.0
ai-edge-torch==0.4.0
astunparse==1.6.3
certifi==2025.6.15
charset-normalizer==3.4.2
exceptiongroup==1.3.0
filelock==3.18.0
flatbuffers==25.2.10
fsspec==2025.5.1
gast==0.6.0
google-pasta==0.2.0
grpcio==1.73.0
h5py==3.14.0
idna==3.10
immutabledict==4.2.1
iniconfig==2.1.0
jax==0.6.1
jaxlib==0.6.1
jinja2==3.1.6
keras==3.10.0
libclang==18.1.1
markdown==3.8
markdown-it-py==3.0.0
markupsafe==3.0.2
mdurl==0.1.2
ml-dtypes==0.5.1
mpmath==1.3.0
namex==0.1.0
networkx==3.4.2
numpy==2.1.3
nvidia-cublas-cu12==12.4.5.8
nvidia-cuda-cupti-cu12==12.4.127
nvidia-cuda-nvrtc-cu12==12.4.127
nvidia-cuda-runtime-cu12==12.4.127
nvidia-cudnn-cu12==9.1.0.70
nvidia-cufft-cu12==11.2.1.3
nvidia-curand-cu12==10.3.5.147
nvidia-cusolver-cu12==11.6.1.9
nvidia-cusparse-cu12==12.3.1.170
nvidia-nccl-cu12==2.21.5
nvidia-nvjitlink-cu12==12.4.127
nvidia-nvtx-cu12==12.4.127
opt-einsum==3.4.0
optree==0.16.0
packaging==25.0
pillow==11.2.1
pluggy==1.6.0
protobuf==5.29.5
pygments==2.19.1
pytest==8.4.0
requests==2.32.4
rich==14.0.0
safetensors==0.5.3
scipy==1.15.3
setuptools==80.9.0
six==1.17.0
sympy==1.13.1
tabulate==0.9.0
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-io-gcs-filesystem==0.37.1
termcolor==3.1.0
tomli==2.2.1
torch==2.5.1
torch-xla2==0.0.1.dev202412041639
torchaudio==2.5.1
torchvision==0.20.1
triton==3.1.0
typing-extensions==4.14.0
urllib3==2.4.0
werkzeug==3.1.3
wheel==0.45.1
wrapt==1.17.2
```

## Environment details:
- OS: Ubuntu 22.04 (running inside a devcontainer)
- Architecture: x86_64

> [!NOTE]
> I’ve also confirmed that the conversion works on Docker Desktop for Mac.
> Mac Book Pro M3 Max  
> Docker Desktop for Mac v4.37.2

**Comment by pkgoogle** [comment]
Hi @kadu-v, sorry I'm having trouble figuring how you are running this on your phone? Is it with pytorch in a container on your phone, and it uses your phone's GPU? Perhaps directly in Termux? or some other situation I'm not fully aware of.

**Comment by aravindmurali22** [comment]
Hi @suleshahid @turbotoribio , following up on this thread, is there any update on this issue? Thanks!
